# Generated by Django 4.2.3 on 2023-08-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_ceo_customuser_is_hod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mailing_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature_images/'),
        ),
    ]
