# Generated by Django 4.2.4 on 2023-08-16 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_unit_customuser_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
