# Generated by Django 4.2.4 on 2023-08-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_unit_unit_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.unit'),
        ),
    ]
