# Generated by Django 4.2.4 on 2023-08-16 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_unit_unit_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_users', to='accounts.unit'),
        ),
    ]
