# Generated by Django 4.2.4 on 2023-08-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RWF', 'RWF')], default='RWF', max_length=3),
        ),
    ]
